pygae/galgebra

.gitignore, .travis.yml, README.md, doc/python/BACCAB.py, doc/python/Dirac.py, doc/python/Dop.py, doc/python/EMWaves.py, doc/python/LinearTrans.py, doc/python/Ltrans.py, doc/python/LtransInst.py, doc/python/ReciprocalBasis.py, doc/python/SphericalCoordinates.py, doc/python/TensorDef.py, doc/python/submanifold.py, doc/python/verify_all.ipynb, galgebra/__init__.py, galgebra/ga.py, galgebra/lt.py, galgebra/metric.py, galgebra/mv.py, galgebra/printer.py, galgebra/utils.py, setup.py, test/test_mv.py, test/test_test.py
This is a work-in-progress for the release of 0.4.3 which is discussed in #10 and https://github.com/brombo/galgebra/pull/42#issuecomment-462263950 .
This PR includes the following:
=> 0.4.3 release

README.md
Use the `master` branch instead of `nbsphinx`.
-----
[View rendered README.md](https://github.com/waldyrious/galgebra/blob/patch-1/README.md)
=> README: fix image links

README.md, doc/changelog.rst, doc/conf.py, doc/index.rst, doc/readthedocs-pip-requirements.txt, setup.py
This is a  work-in-progress for the release of 0.4.4 which is based on [Milestone 0.4.4](https://github.com/pygae/galgebra/milestone/1), with the following additional tasks to complete:
Work after this PR:
=> Release 0.4.4

galgebra/metric.py
This uses the numpy docstring style, which is already enabled in the sphinx config
=> Fix the docstring of `metric` to render properly

galgebra/ga.py
Unfortunately napoleon doesn't allow us to group our members together as was intended here - so we have to abandon numpydoc in this class and use `.. attribute` directly, which is quite verbose. Also frustratingly, we cannot use headings inside `Ga.__doc__`, so have to make do with `..rubric::`.
This also adds backticks and latex rendering in many places where it aids readability.
Rendered output: [before](https://galgebra.readthedocs.io/en/latest/generated/galgebra.ga.html#module-galgebra.ga), [after](https://external-builds.readthedocs.io/html/galgebra/51/generated/galgebra.ga.html#module-galgebra.ga)
=> Cleanup many docstrings in ga.py

galgebra/ga.py, galgebra/lt.py, galgebra/mv.py
The typical python function signature is `f(*args, **kwargs)` not `f(*kargs, **kwargs)`.
The `kw` in `kwargs` stands for `keyword`, but the first `k` doesn't mean anything.
=> Rename kargs to args

galgebra/mv.py
Extracted from gh-57 to make the diff there readable
=> Tidy `Mv.make_x` methods and make them private

galgebra/mv.py
Depends on gh-58 in order to have a readable diff
---
These don't need to mutate any state, and they way they did before made the iterative approach in make_multivector quite confusing.
The functions now return a raw sympy expression, which is assigned to `self.obj` in a single place.
This also adds errors to the paths that didn't set anything at all.
The one assignment to `self.grade_i` was pointless, as it was overwritten later anyway
=> Make `Mv._make_x` functions private and static

galgebra/mv.py
These are not documented or used anywhere outside of __init__.
Nor are they useful, since the caller can just construct themselves a new `Mv` instead of reusing the old one.
Now that they are private, we can convert these comments into docstrings without them appearing on readthedocs.
Also split from #57
=> Make the `Mv.make_x` functions private

galgebra/mv.py, test/test_mv.py
Previously this would cause weird and surprising swaps between basis representations.
=> Make `blade_rep` and `base_rep` non mutating

galgebra/ga.py, galgebra/lt.py, galgebra/mv.py
This change leaves the behavior of `Ga.dot_mode` and `Ga.dot` alone, but replaces all the internal uses of these variables with new `left_contract`, `right_contract`, and `hestenes_dot` methods.
Passing the mode as an argument instead means that this code becomes (more) threadsafe.
=> Avoid using `dot_mode` to determine which dot product to call

galgebra/lt.py, galgebra/mv.py
This:
* Uses math and code formatting where appropriate
* Promotes some comments to docstrings
* Ensures dead commented out code does not end up as a docstring
* Fixes some typos
* Merges docstrings duplicated between `cls.__doc__` and `cls.__init__.__doc__`
Results:
https://external-builds.readthedocs.io/html/galgebra/56/generated/galgebra.mv.html
https://external-builds.readthedocs.io/html/galgebra/56/generated/galgebra.lt.html
=> Fixup docstrings for mv and lt

README.md
This repo no longer exists.
Replace links to that repo with waybackmachine links.
-----
[View rendered README.md](https://github.com/pygae/galgebra/blob/fix-readme-links/README.md)
=> Fix dead links to brombo/galgebra in the readme

galgebra/ga.py, galgebra/lt.py, galgebra/mv.py
This saves a few lines, and makes the loops easier to reason about.
Also simplifies a call to `itertools.product` to reduce the length of a long line
=> Simplify loops using `enumerate` and `range`

galgebra/ga.py
This:
* Removes the always-empty:
* `Ga.mul_table`
* `Ga.wedge_table`
* `Ga.dot_table`
* `Ga.left_contract_table`
* `Ga.right_contract_table`
* Rewrites the unused `auto_update_dict` to be `lazy_dict`, which uses `dict.__missing__` for simplicity
* Changes `Ga.mul_table_dict` and similar to be lazy, which is better than it starting off completely empty
* Adds documentation for the other `Ga.*_table_dict` attributes
* Removes the `func` argument from `update_and_substitute`, which is now usable with a dictionary alone. I don't think this is really public API, so this should be fine.
=> Clean up the multiplication table attributes on Ga

galgebra/ga.py, galgebra/metric.py
The user has no reason to ever call these methods - they're called at construction, and they have no return value.
Also makes some internal caching flags private - the user should be calling the function directly, rather than poking around in the cache.
=> Make internal caching and construction methods  private

galgebra/ga.py, galgebra/lt.py, galgebra/metric.py, galgebra/mv.py, galgebra/printer.py
These modules do not make sense to run from the command line, so should not have these lines.
At any rate, these lines do nothing.
=> Remove `__name__ == '__main__'` check from modules

galgebra/mv.py
`__add_ab__` appeared in [a very old `python-dev` discussion](https://mail.python.org/pipermail/python-dev/2000-August/008000.html), but as far as I can tell has never been respected, and certainly is not respected in any supported version of python - the correct spelling is `__iadd__`.
Given that `galgebra` is working fine without these methods, and sympy does not define any in place operators, it seems wise to just remove them.
=> Remove non-existent magic methods

galgebra/ga.py
Before this change, grads were constructed:
* twice during `__init__`
* each time the user called `ga.mv()` with no arguments
* each time the user called `ga.grads()`
After this change, grads are constructed:
* once during `__init__`
=> Construct the grads only once

galgebra/ga.py
There's not need to do messy indexing here, we already have a list of blades by grade - let's use it!
At this point the comment and the code become the same, also ditch the comment.
Extracted from a future patch that adds the scalar to `self.blades_lst`.
=> Use blades instead of blades_lst

galgebra/ga.py, galgebra/mv.py
Before this change, every call to `Ga.mv` would reassign `mv_I`, `mv_basis`, and `mv_x`. There is no reason to do this, if a user asked for `.mv('A', 'vector')` they were not expecting to get a new (but identical) `mv_I`.
Since `Ga.__init__` called `self.mv` anyway, the previous approach didn't actually result in lazy computation anyway.
This change inlines the content of `Mv.setup` into `Ga.__init__`, and changes `Mv.setup` to just pull out the properties computed by `__init__`.
---
Extracted from #76
=> Don't run `Mv.setup` every time an Mv is created

galgebra/ga.py
This reduces the indentation level by a bunch, which should hopefully make the codebeat CI tool happier
This blocks #90, which is currently failing due to this nesting
---
Working as intended, critical error is no more:
=> Extract a helper function from `_build_bases`

galgebra/ga.py
`Ga.iobj` was confusingly `Ga.e.obj` and not `Ga.i.obj`.
`Ga.e_obj` was just an alias of `Ga.e.obj`, which bizarrely only existed if the GA had a coords argument.
There are still plenty of ways to spell the pseudo-scalar, all of them clearer than this way:
* Normalized:
* `ga.I()`
* `ga.i`
* Unnormalized:
* `ga.E()`
* `ga.e`
* `ga.mv_I` (!)
=> Remove Ga.iobj and Ga.e_obj

galgebra/mv.py, test/test_mv.py
If `Mv` is passed the wrong number of positional arguments, it used to either silently ignore them, or crash with an unclear message.
This would either confuse users, or mask bugs. With this change, it becomes a `TypeError` to pass either too many or too few parameters.
=> Raise TypeError for bad arguments to `Mv`

galgebra/ga.py, galgebra/mv.py, test/test_mv.py
Split from #63 (which has also been rebased), in a non-intrusive way that doesn't attempt to address #64
This:
* Since the scalar 1 is a blade of grade 0:
* Changes `Ga.blades[0]` from `[]` to `[1]`
* Changes `Ga.blade_super_scripts[0]` from `[]` to `['']`
* Changes `Ga.bases[0]` from `[]` to `[1]`
* Changes `Ga.indexes[0]` from `()` (no indices) to `((),)` (a single empty index)
* Introduces some private lists, which include this scalar element, and use them throughout internally:
* `Ga._all_blades_lst` (Previously called `blades_lst0`, which has been removed)
* `Ga._all_bases_lst`
* `Ga._all_indexes_lst`
* `Ga._all_mv_blades_lst`
gh-64 tracks changing the public lists to include the scalar, which would be a breaking change
* As a result of using these internally, the following …
=> Correct information about blades of grade 0

galgebra/mv.py
This eliminates some special-casing in _make_mv and _make_spinor
Note that to avoid making gh-81 worse, we now need to expicitly only allow strings
Follows on from #90
=> Implement _make_scalar in terms of _make_grade

galgebra/mv.py
Some small cleanup before stricter kwarg validation
=> Simplify kwarg parsing in _make_grade

galgebra/deprecated.py, galgebra/mv.py, galgebra/utils.py, test/test_mv.py
Also add much better documentation for construction (https://external-builds.readthedocs.io/html/galgebra/97/generated/galgebra.mv.html#galgebra.mv.Mv)
---
Builds upon #96, posting now to solve any CI issues
Bonus!
=> Be stricter about kwargs to Mv.__init__

galgebra/ga.py
Merges the duplicate grade lookup rules between `dot_product_basis_blades` and `non_orthogonal_dot_product_basis_blades`.
This also fixes some return values to be zero instead of 0, not that that matters too much.
Since #134 didn't work, trying to dig deeper to work out where things break.
---
Not even aiming for this, but:
=> Merge duplicate grade selection code

galgebra/ga.py
Split from an earlier PR (#99) that failed CI. This part strikes me as the part that wasn't wrong.
It's not particularly useful, but this now means that `ga.dot_table_dict[S(1), S(1)]` now returns 0 and not 1.
This does not affect the output of the `hestenes_dot` function, it just brings the table in line with it.
=> Fold the exclusions of scalars from the hestenes dot product into the table

galgebra/ga.py
It's possible this will be marginally slower, but it makes everything much easier to read.
=> Remove special-cases for scalars in contractions

examples/Terminal/rotations.py, galgebra/metric.py, galgebra/mv.py
It is much easier to reason about multivector objects if they are are not mutated unexpectedly.
This changes the following functions to not mutate their arguments. Any code relying solely on the return value will be unaffected:
* `Metric.applymv`
* `Mv.diff`
* `Mv.simplify`
* `Mv.expand`
* `Mv.collect`
This also changes `Mv.Mv_str` and `Mv.Mv_latex_str` to not mutate their multivectors when they are printed - this is super surprising behavior
cc @meuns
=> Remove assignments to mv.obj

galgebra/ga.py
After the previous PR's removing special cases for scalars (#134, #99), it's now apparent that `_dot` is a trivial function that can be inlined at its call sites
=> Eliminate `_dot`, which is now easy to inline into `Mul`

galgebra/ga.py
This is already handled just fine as part of the substitution process, and doesn't seem like a particularly worthwhile case to optimize.
If we do care care about optimizing it, the optimization would be more effective inside `update_and_substitute` anyway.
=> Eliminate special-cases for multiplication by zero

galgebra/mv.py
Introduced in gh-141, which removed all uses of this variable but forgot to remove it.
=> Remove unused variable found by LGTM

examples/ipython/inner_product.ipynb, galgebra/mv.py
Continues from #134 and 6cc530c8f323bce17cf6290a42ca1c2fd532591d
This also changes some sympy zeros to multivector zeros, which means that `(A | scalar) ^ (B | scalar)` is not a TypeError, as it was before:
```python
>>> s = g.mv(1, 'scalar')
>>> (ex | s) ^ (ey | s)
TypeError: unsupported operand type(s) for ^: 'Zero' and 'Zero'
```
=> Remove yet more special-casing of the hestenes dot product

galgebra/mv.py
By default `sum([])` returns the `int` 0, but for sympy we ought to return `S(0)` or `Mv(0)`, so that other operations continue to work.
=> Return appropriate zeros on an empty sum

galgebra/mv.py
This makes `Sdop.__radd__` match `Dop.__radd__`, and fixes a typo in the if statement.
Reduced version of gh-157, which introduced no non-trivial changes in uncovered code.
I know this is only 50% patch coverage, but it's also only two lines!
=> Fix obvious typos in Sdop.Add

galgebra/mv.py
Storing a ga globally like this isn't a good idea.
Additionally, it's very confusing that both `some_dop.ga` and `some_dop.Ga` exist, but the former is always `None`.
If anyone was actually using this, they can always use
```python
import functools
Pdop = functools.partial(Pdop, ga=my_ga)
Sdop = functools.partial(Sdop, ga=my_ga)
Dop = functools.partial(Dop, ga=my_ga)
```
=> Remove unused and undocumented setGa method

.circleci/config.yml, README.md, setup.py
Python 3.4 was end of life back in march, and there's little value in continuing to support it.
Removing the CI run will save some PR time and electricity :)
Also modifies the setup.py to refuse to install on 3.4.
-----
[View rendered README.md](https://github.com/eric-wieser/galgebra/blob/drop-python-3.4/README.md)
=> Drop support for python 3.4

galgebra/metric.py, galgebra/mv.py
This introduces a new `linear_expand_terms` function with the same meaning as the above
The original was incorrect because the early return paths did not respect the mode argument.
By using this function through mv.py, we can remove a line or two from a lot of functions
=> Replace the broken linear_expand(x, mode=False)

.circleci/config.yml, test/.nbval_sanitize.cfg
Relates to #94, although lets start with the last 2.7 release
=> Add a sympy 1.5 run for CircleCI

galgebra/ga.py
`_dot` was removed in gh-142, but when inlining, this call site was missed.
Coverage will be zero, but I'll handle adding that in #140
=> Fix AttributeError in er_blade

galgebra/deprecated.py, galgebra/ga.py
This reduces the chance of obtaining imprecise floating-point numbers when dividing at the call site.
Far from an exhaustive replacement.
=> Use sympy scalars in more places

galgebra/mv.py, test/test_differential_ops.py
See individual commits for details
=> Add tests for Dop and fix bugs found

galgebra/mv.py
This has nothing to do with differential operators, and isn't used or documented.
In the very unlikely event that anyone was using this, the builtin `itertools.chain.from_iterable` provides similar functionality.
=> Remove unused `flatten_one_level` function

galgebra/mv.py
Closes gh-81.
This makes this consistent with the `even` and `mv` constructors.
=> Forbid passing coefficients to odd Mvs

doc/changelog.rst
Continuing from #146, adding release notes for:
* #151
* #164
* #165
* #167
* #169
* #170
* #172
* #175
* #177
* #180
https://external-builds.readthedocs.io/html/galgebra/186/changelog.html
=> Update release notes from some previous PRs

galgebra/mv.py, test/test_differential_ops.py
The previous code was nonsense - `len(args[0]) == 1 and isinstance(args[0],Symbol)` was never true, as `Symbol.__len__` is undefined.
This also makes it illegal to pass extra ignored arguments to `Pdop`.
Finally, this deprecates `Pdop(None, ga=ga)` as an alias for `Pdop({}, ga=ga)` - there's no reason to have two ways to spell the same thing, and the second is more natural.
=> Fix Pdop and Sdop shorthands

galgebra/mv.py
This:
* Raises NameError, because `true` should be spelt `True`
* If fixed, raises `AttributeError` for `ga.pdx`
* Is attempting to set `ga.lgrad` as a weird alias of `ga.grad`
* Is just a weird way to spell `ga.grads()`
=> Remove the broken and redundant Dop.basic

galgebra/ga.py
Previously:
* `Ga.pdop` was unusable, since it would call `Pdop.__init__` with a `tuple`, but that function expects a `Symbol` or `Dict`
* `Ga.sdop` was not callable with one argument, since it would pass on an unwanted `None` argument to `pdiffs`
Also groups these functions to be adjacent, for clarity
---
And a second commit:
---
Previously, `sm`, `lt`, and `mv` would all ignore a `ga` kwarg if passed.
Now it is an error to pass the argument.
The code is simpler too.
=> Fix the alias operator constructors on Ga objects

galgebra/mv.py, test/test_differential_ops.py
Before this change, any addition other than `Sdop + Sdop` would raise a NameError, since the variable `coef` is not defined in the `elif` and `else` branch.
The intent of the old code was fairly clear - it was to insert a multiplicative term for `sdop2.Ga.Pdop_identity`, such that `(sdop + 2)(x) == sdop(x) + 2*x`, which is reflected by the repr in a shell.
This change just copies the code from `Dop`, which succeeds in doing exactly the same thing
This also adds a bunch more tests for both Sdop and Dop operations
=> Fix heterogeneous sdop.Add 

galgebra/mv.py
This code is unreachable, because the contract of `cls.__mul__(a, b)` is that `isinstance(a, cls)` is _always_ `True`
=> Remove dead code

.circleci/config.yml
Extracted from #37 . This will only partially enable SymEngine.
=> Add a Py 3.7 build with SymEngine partially enabled

galgebra/mv.py, test/test_differential_ops.py
__ne__ is needed by python 2 (https://stackoverflow.com/q/4352244/102441), else it defaults to `x is not y`
Also:
* move some tests that ended up in the wrong place after a merge/rebase
* use the helper alias methods in `Ga` to increase coverage
=> Fix the broken `Sdop.__eq__`, and add the missing `__ne__` operators.

galgebra/ga.py, galgebra/mv.py, test/test_differential_ops.py
These attributes all have shorter spellings, and now that `__eq__` and `__ne__` work, there's little need to cache them.
=> Deprecate Pdiffs, sPds, and Pdop_identity

galgebra/ga.py, galgebra/mv.py, test/test_mv.py
Every member we can remove from `Ga` makes galgebra easier to understand
=> Deprecate compatibility members of Ga objects

galgebra/lt.py, galgebra/mv.py
The code was probably written this way before because `__ne__` was not correct on python 2.
This was fixed in gh-197
=> Don't compare the name of the GA when GA.__eq__ already does this

galgebra/mv.py
This object is supposed to keep terms as scalars, so this promotion was nonsensical.
Introduced by me in 8f2e91fc35d0766b386f3a0c31d2c9921aeee8b4.
=> Don't promote scalars to multivectors in Sdop

galgebra/mv.py
This function doesn't do anything, and causes LGTM warnings.
API surface that doesn't work is just confusing to users.
The intention of this function was probably something like:
```python
def blade_rep(self):
return Dop(_consolidate_terms(
(coef.blade_rep(), pdiff) for coef, pdiff in self.terms
), cmpflg=self.cmpflg, ga=self.Ga)
```
However, constructing a Dop with non-blade coefficients is unlikely in the first place, so if we add this function it is very unlikely that anyone would need it.
Closes gh-147
=> Remove Dop.blade_rep

galgebra/lt.py, galgebra/metric.py, test/test_lt.py
Fixes #105 .
- Added tests for reproducing #105
- `linear_expand` no longer accepts `Mv` as `expr`
- `Dictionary_to_Matrix` automatically converts `Mv` to `Expr`, taking care of #105 and the test case in `examples/Terminal/lt_test.py`
=> Fix linear transformation created with Mv matrix

galgebra/metric.py, galgebra/mv.py
In principle this is a breaking change, but I doubt anyone is using this function anyway.
We no longer use it internally.
Will need a changelog entry listing this as a removed function.
=> Remove the now-unused `test_init_slots`

galgebra/metric.py
This function is used to parse the `bases` argument to `Ga`, which is otherwise undocumented.
https://external-builds.readthedocs.io/html/galgebra/214/generated/galgebra.metric.html#module-galgebra.metric
=> Add documentation for `metric.symbol_list`

galgebra/deprecated.py, galgebra/ga.py, galgebra/lt.py, galgebra/metric.py, galgebra/mv.py, galgebra/printer.py, test/test_test.py
A return statement on the last line of a function, with no value to return, is a no-op.
There's already a very clear indicator that the end of the function has been reached anyway - the indentation level.
Found by looking for `^ {8}return$`, and manually vetting each one for readability.
A few in nested functions remain.
=> Remove trailing empty return statements

galgebra/mv.py
Rather than deferring explicitly, we can exploit that `dop.__rmul__(mv)` will be called if `mv.__mul__(dop)` returns `NotImplemented.
=> Use NotImplemented to defer MV operations to Dop

galgebra/__init__.py, galgebra/dop.py, galgebra/ga.py, galgebra/mv.py, test/test_differential_ops.py
This breaks the file roughly in two, which seems like a nice breakdown.
Splitting further is probably harmful, since these three classes are tightly related.
No code changes beyond moving lines and adjusting imports.
Things to check:
=> Extract the differential operators to their own (private) file

galgebra/dop.py
Sympy symbols are not sortable by default, they have to be sorted using the `sort_key` member.
=> Fix crash in Pdop.repr with multiple variables

test_requirements.txt
This reverts commit f307c2554b4f070daa3201efbc89bf4f6e8e070c (gh-152)
The upstream issue, https://github.com/computationalmodelling/nbval/issues/129, has been resolved.
=> Revert "Pin the version of coverage for nbval compatibility"

galgebra/dop.py, galgebra/mv.py, test/test_differential_ops.py
~~Built on top of #133, probably should wait for #223.~~ ~~Includes #225, that should be merged first.~~
`_eval_derivative_n_times` is a method name stolen from sympy.
sympy will ignore it until we start subclassing sympy objects, but it communicates the intent well.
This comes at a minor performance hit to things like `Pdop({x: 1, y:2}) * Pdop({x: 1, y:2})`, which now makes one extra intermediate dict copy. I think the line savings are clearly worth it.
---
This probably fixes a bunch of cases that didn't work before, and definitely makes some previously nonsensical results (eg `mv * pdop == mv`) errors.
This also reduces the line count a little bit (ignoring the new tests)
=> Reduce coupling between the Dop classes

.circleci/config.yml, galgebra/deprecated.py, galgebra/lt.py, setup.py
Removes the stale `python-3.7-sympy-1.4` job which was identical to `python-3.7-sympy-1.3`.
=> Add CI for python 3.8

galgebra/dop.py, galgebra/mv.py, test/test_differential_ops.py
This hopefully makes the overloaded construction logic a bit easier to follow, and results in better error messages and types when you get it wrong.
=> Improve errors in dop constructors

.circleci/config.yml, galgebra/__init__.py, galgebra/utils.py, setup.cfg, setup.py
In order to keep this diff small, this ignores every warning we currently have, rather than fixing them.
This is enough to prevent the style drifting further from flake8 unnoticed.
Future patches can aim to cut down the warnings at a file-by-file basis.
CI is set up so that if linting fails, no tests are run [see here](https://circleci.com/workflow-run/ebb57ca9-eb79-4b3a-ab7d-067ef378ebc0)
=> Run flake8 against the source, with a very generous ignore list

doc/changelog.rst, galgebra/ga.py, galgebra/lt.py, test/test_test.py
By adding an OrderedBiMap class, we can squash 8 members down to 2.
=> Deprecate a bunch of similar members of `Ga`

galgebra/mv.py, test/test_mv.py
This means that all of the calling conventions of `sympy.Basic.subs` are supported
I think this covers one of the changes from #62.
=> Add support for passing other forms of argument to `Mv.subs`

doc/changelog.rst, galgebra/ga.py, test/test_test.py
It's not clear if they're intended to be public, but this errs on the side of caution and deprecates them.
Overall, this collapses 8 attributes down to 3.
Combined with #245 and #64, that brings us up to 15 members of `Ga` deprecated.
=> Deprecate more useless attributes of `Ga`

galgebra/metric.py, test/test_mv.py
`n` is an integer, so `n / 2` evaluates to a `float`.
This then can't be simplified by sympy.
Using `S(2)` here forces the result to be rational.
Previously this test gave `abs(B*B)` as `(B__12**2 + B__13**2 + B__23**2)**1.0`
=> Avoid injecting a float into a sympy expression

doc/conf.py
Even if the order still ends up bad, this gives us the power to more easily change it in future, simply by reordering the source code.
Demonstrating where this provides value, the [dot products](https://galgebra--254.org.readthedocs.build/en/254/generated/galgebra.ga.html#galgebra.ga.Ga.hestenes_dot) are now all documented adjacent to each other.
=> Show member documentation in source order

setup.py
Notably:
* The readme content is now included in PyPI
* Alan's name is no longer associated with Hugo's email address
* The PyPI sidebar will now link to our issue tracker and documentation
* The __version__ loading is a little more resilient to unusual value of cwd
=> Various improvements to setup.py

galgebra/mv.py
These didn't appear to be used from any examples or tests, and don't make much sense - it would be weird to configure `Mv` to use latex when the rest did not.
Inspired by splitting up #258.
=> Remove Mv.Format, Mv.latex_flg, and Mv.restore

galgebra/mv.py, test/test_printer.py
It is not safe to call `str()` from within `Mv_str`, as `str()` is overloaded by `ga.printer` to sometimes mean `latex()`.
Previously, `GaPrinter().doprint(mv)` would return latex despite being an explicit request for the non-latex format.
Split from #258
=> Ensure the latex printer is not invoked when the string printer is requested

doc/python/BACCAB.py, examples/ipython/printing-galgebra.ipynb
- added "4 ways to print in GAlgebra", an overview of different ways of printing as a CI test
- also reproduced a few printing bugs to fix later, including
- incorrect handling of \wedge
- printed raw string instead of LaTeX in lists/tuples
=> Add an overview of different ways of printing as a CI test

galgebra/mv.py, galgebra/printer.py
This if is already present in `Mv_latex_str` and `Mv_str`, there is no need to perform it twice.
=> Move an if from the printer

galgebra/ga.py
`Ga()` and `Sm()` end up calling `str(some_sympy_object)` in multiple places.
Previously, this went through our custom printer, which meant we had to temporarily disable latex printing.
Making `str(some_sympy_object)` go through our printer was a mistake that interfered with sympy internals, so a previous commit made it no longer do that.
As a result, we no longer need to touch the printer in `__init__`.
---
~~First commit is #260, second commit is #258. Will rebase once those are merged.~~
=> Remove the no-longer needed print reconfiguration in Ga.__init__

galgebra/printer.py
I can only assume `regrep` was some portmanteau of `regexp` and `grep`.
=> Remove weird name for the `re` module

galgebra/dop.py, galgebra/lt.py, galgebra/mv.py
This function is just `GaLatexPrinter().doprint(x)` with some extra behavior for whether `x` is a list.
`self` is not a list in any of these places.
https://github.com/pygae/galgebra/blob/6c3856856ddcf1d5bbabe5f26b749c4bea85cca4/galgebra/printer.py#L973-L983
Brought on by https://github.com/pygae/galgebra/pull/264#issuecomment-621884504
=> Remove all callers of `printer.GaLatexPrinter.latex`

galgebra/dop.py, galgebra/lt.py, galgebra/mv.py, galgebra/printer.py
As described by @asmeurer in https://github.com/pygae/galgebra/pull/258#issuecomment-622126220, there is no need for us to register our objects this way.
This PR include #270 as its first two commits, but is probably fine to merge all at once.
=> Use the builtin hooks in sympy printers

galgebra/mv.py
Cherry-picked from @meuns' branch (#68)
We can skip a check here, since we know `Ga.mv_blades` will contain only blades.
No behavior change, but likely a small performance boost.
=> Avoid checking whether the basis blades are blades

galgebra/metric.py
These are reassigned before they are used.
This should fix some LGTM warnings.
=> Remove some overwritten variables

galgebra/metric.py
I'd argue that by reducing the number of local variables, this makes things more readable
=> Convert more loops to comprehensions in metric.py

galgebra/ga.py
`indexes_to_blades` is a list of tuple, but this usage was indexing it with a tuple, which is a TypeError.
I don't think this code is even covered in CI, but this is definitely at least less wrong.
=> Fix a use of the incorrect variable

galgebra/ga.py
The special case in the `grade > 2` branch was previously needed because `indexes_to_blades_dict` did not contain the scalar element.
Also switches to using `reduce` for a bit of clarity.
The other cases were there for optimization purposes. It's not clear whether they were worthwhile.
Fixes gh-282
=> Remove the special cases in Ga.blade_derivation

doc/galgebra_guide.rst
Replaced using the regex `/’.+?’(?!s)/'\1'/g`
=> Use straight quotes for pythoncode examples

doc/galgebra_guide.rst
These were present in the latex, but lost in the markdown conversion.
=> Add missing code samples referenced by the surrounding text.

doc/module-components.rst
In a future PR we should replace some of these `..method`s with `..automethod`s, and similar for classes and functions.
We use `:noindex:` to prevent clashes with the api documentation.
=> Use sphinx directives to describe function and class names

doc/module-components.rst, galgebra/printer.py
This is an example of how gh-300 can be addressed.
Before: https://galgebra.readthedocs.io/en/latest/module-components.html#latex-printing
After: https://galgebra--301.org.readthedocs.build/en/301/module-components.html#latex-printing
=> Move documentation for a single printer function to the source code

doc/module-components.rst, galgebra/ga.py, galgebra/mv.py, galgebra/printer.py
This picks off most of the very easy docstrings, include the wrapper functions that just forward to a multivector method.
A couple of methods in printer.py got proper `sphinx.ext.napoleon` docstrings, and a few others got docstrings for the first time.
xref gh-300
=> Merge some docstrings from module-components and the api

galgebra/_utils/parser.py, galgebra/printer.py
This state is just an artefact of the weird two-stage printer API, and isn't part of the parsing at all.
=> Remove global mutable state from `galgebra._utils.parser`

galgebra/ga.py, test/test_test.py
Also deprecates passing `mode="nonsense"`, and improves the docstring.
Split from #249
=> Add test for `ga.ReciprocalFrame`

galgebra/metric.py
Also deprecate `Metric.derivatives_of_g`, which does nothing any more.
Split from gh-252
=> Use cached_property for some simple members of metric.

doc/galgebra_guide.rst
This was a mistake in the previous commit, which caused two copies of the docstring to appear.
=> Remove stray docstring that is already populated by autofunction

galgebra/_backports/typing.py, galgebra/ga.py, galgebra/mv.py, galgebra/printer.py
This also makes some fixes regarding type annotations found by mypy, including reusing a variable with different types each time.
MyPy also complained about using `_X = TypeVar('X')`, so instead this uses the name without an underscore, but deletes it as soon as it is no longer needed.
=> Improve type annotations

doc/module-components.rst, galgebra/lt.py
Lt: https://galgebra--321.org.readthedocs.build/en/321/module-components.html#linear-transformations
| before | after |
|:--:|:--:|
| ![image](https://user-images.githubusercontent.com/425260/81399864-bd0f4980-9123-11ea-8403-44b896339f75.png) | ![image](https://user-images.githubusercontent.com/425260/81400126-58082380-9124-11ea-9c49-d18295638f55.png)
Mlt: https://galgebra--321.org.readthedocs.build/en/321/module-components.html#basic-multilinear-function-class-functions
| before | after |
|:--:|:--:|
| ![image](https://user-images.githubusercontent.com/425260/81399802-96e9a980-9123-11ea-9ce8-c6a963946e66.png) | ![image](https://user-images.githubusercontent.com/425260/81399814-a1a43e80-9123-11ea-9dc8-2956c3c7a8b3.png)
xref gh-300
=> Move method docstrings from rst to python for Lt and Mlt

doc/module-components.rst, galgebra/deprecated.py
These are taken almost verbatim, with some added line wrapping.
Note that the footnote needs to move with them.
| Before | After |
|:--:|:--:|
| ![image](https://user-images.githubusercontent.com/425260/81401548-76bbe980-9127-11ea-9a31-f1e169c57257.png) | ![image](https://user-images.githubusercontent.com/425260/81401519-6572dd00-9127-11ea-8325-0834f0a4950c.png) |
There's an open sphinx issue about footnotes ending up in a bad place, and I think it's tolerable for now.
xref gh-300
=> Move method docstrings from rst to python for deprecated.MV

doc/python/TensorDef.py, galgebra/ga.py, galgebra/lt.py, test/test_lt.py
This is best reviewed commit-by-commit. The summary is:
1. Revert the parts of fc598df56ac6573248a187d514262f6312b17f31 that started a refactor of `Mlt` that was unfinished. This fixes gh-171.
2. Fix some obvious typos in code that never worked, and add tests.
3. Make the attributes restored in 1. private
=> Make `galgebra.lt.Mlt` somewhat usable again

doc/conf.py
See https://galgebra--328.org.readthedocs.build/en/328/generated/galgebra.mv.html#galgebra.mv.Mv.get_coefs for an example of a working link to `Expr`.
=> Add intersphinx mapping to make sympy references linked [ci skip]

galgebra/ga.py
There is no need to perform an expensive call to `mul` if we know in advance that the result is 0.
=> Exit dot product function early if the grades tell us the result is 0.

galgebra/ga.py
Also fix the misleading code samples in the docstrings, which suggest the keys are `sympy.Mul` instance when in fact they are tuples.
----
Looks pretty ugly, but it's at least correct, and a future sphinx version will fix the long qualified names:
=> Add type arguments to lazy_dict, and use them on properties.

galgebra/ga.py, test/test_test.py
For each product, this merges together:
* `ga.prod`
* `ga.prod_table_dict` -> `ga.prod.table_dict`
* `ga.prod_basis_blades` -> `ga.prod.basis_blades`
This removes a lot of boilerplate construction of lazydicts, and means it's easier to add more products in future, such as a scalar product or vee product.
Related to #196. This leaves behind a lot of alias attributes that we could consider deprecating and eventually removing in future:
* `mul_table_dict`
* `wedge_table_dict`
* `left_contract_table_dict`
* `right_contract_table_dict`
* `basic_mul_table_dict`
* `_dot_product_method`
* `dot_product_basis_blades`
* `non_orthogonal_dot_product_basis_blades`
* `wedge_product_basis_blades`
* `non_orthogonal_bases_products`
Almost all of the mathematically interesting code in this diff is just …
=> Extract a helper class to unify the mess of properties associated with each type of multiplication.

doc/changelog.rst, galgebra/ga.py, test/test_test.py
This makes a reasonable dent in #196.
It's fairly likely these weren't intended to be public anyway, but they seem reasonably harmless to expose publically in a nested object.
=> Deprecate another 11 moved members of Ga

doc/changelog.rst, galgebra/ga.py, test/test_test.py
=> Remove Ga.X(), which is a worse spelling of Ga.coord_vec

test/test_lt.py
This provides coverage for #136
=> Add tests for creating Mlt instances from a string

galgebra/lt.py
The rank = 1 code path is just a loop unrolling of the general code path. That's not useful, lets not do it.
Also replaces 0 with S(0), and makes nargs == 0 work for the heck of it by using the initial argument to reduce.
First commit is #337, let's get that in first before merging this, so we can see if the lines this touches are covered.
=> Combine nargs == 1 with nargs < 1

examples/ipython/gsym-printing.ipynb
There are lots of bugs hiding in here relating to printing, felt it would be best to put in a baseline notebook so that I can fix them as I go along.
Bugs include:
* `g` being treated specially
* `det` often being printed incorrectly
* print behavior changing based on whether the printer was enabled yet when the reciprocal blades were computed
* floats creeping into `e_sq`
=> Add a notebook demonstrating weird bugs in the gsym argument

doc/changelog.rst, galgebra/lt.py, test/test_lt.py
This function has a typo in the name, and is a remnant of a workaround for old and dangerous printer behavior.
At any rate, it is unnecessary as we already compute this value elsewhere.
Depends on #136 and #337
=> Deprecate Mlt.extact_basis_indexes [sic]

examples/ipython/gsym-printing.ipynb, galgebra/ga.py
These was caused by a floating point division in an exponent. Since `n` is an integer, `n*(n+1)` is always even, so we can use floor division and end up with an `int` rather than a `float`.
=> Remove the `1.0` floats that snuck into ga.e_sq

setup.cfg
No idea why coverage changed, but I don't think it matters here.
=> Do not generate `reflect_test.tex` every time any test is run

galgebra/printer.py
Cherry-picked from abrombo/master (#62). The rendered latex for this comment would be:
Of course, this string is not used at all, so this doesn't matter.
=> Remove a pointless docstring that is not attached to anything

galgebra/printer.py
This makes things more readable, and shrinks the diff a little from abrombo/master, making an eventual printer merge easier (xref #62).
=> Use a raw string for printer.ip_cmds

examples/ipython/gsym-printing.ipynb, galgebra/atoms.py, galgebra/ga.py, galgebra/metric.py, galgebra/printer.py
~~We should merge #339 first, putting up now to trial CI.~~
See commit messages for an explanation of this change.
=> Fix printing bugs around the gsym argument to Ga

galgebra/ga.py, galgebra/lt.py, galgebra/metric.py
This removes a lot of the `_build_x` methods, and allows the documentation for the properties of `Ga` to be put right by their implementation.
Will probably need a few revisions to pass CI.
Working on getting [the docs](https://galgebra--252.org.readthedocs.build/en/252/generated/galgebra.ga.html) to show the annotations. (edit: this requires a patch to sphinx, which won't be released for a while)
This seems to go with the spirit of https://github.com/pygae/galgebra/pull/78#pullrequestreview-323373088
=> Use cached_property for as many parts of `Ga` as possible

galgebra/printer.py
Previously this function used a global variable to track working state.
There is no reason to do this, we can just use a return value.
=> Make `galgebra.printer.ostr` threadsafe

galgebra/printer.py
This code is unreachable, because `GaPrinter().doprint(x)` dispatches via `type(x).__name__`, and `Matrix.__name__` is actually `MutableDenseMatrix`.
If you do run this code, the identity matrix prints as `\n[1,0,0,1]` which is nonsense anyway.
=> Remove GaPrinter._print_Matrix

galgebra/printer.py
A variant of this function is now in the standard library as of Python 3.3.
I'd argue we don't need to deprecate this, it's hard to consider it public API.
=> Replace `galgebra.printer.find_executable` with `shutil.which`

test/test_printer.py
These tests would sporadically fail on python 3.5, since the order of a dictionary is undefined.
It's simplest just to skip the assertion on these python versions, it ensures we at least exercise the code path.
=> Do not fail on unordered dictionaries on python 3.5

test/.nbval_sanitize.cfg
I made a PR to sympy that affected how tuples print out (sympy/sympy#19348)
A failing CI run is here: https://circleci.com/gh/pygae/galgebra/5213?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Fix CI failures on sympy master

examples/LaTeX/FmtChk.py, galgebra/mv.py, galgebra/printer.py
As far as I could tell, none of these do anything. Let's just remove them.
=> Remove unused global printer properties

examples/ipython/Terminal.ipynb
These are caused by ipython deciding to render partial results.
nbval ignores these, and they make it harder to inspect diffs in the ipynb files as they move around randomly.
=> Remove buffering artifacts from Terminal.ipynb

examples/ipython/simple_ga_test.ipynb, galgebra/dop.py, galgebra/lt.py, galgebra/mv.py, galgebra/printer.py
This follows on from #371, and also hitting `Sdop`, `Pdop`, `Lt`, and `Mlt`.
This then moves all the duplicated code to `printer.py`.
As a result of this change, only one line of code outside of `printer.py` uses `GaLatexPrinter.latex_flg`, and it only does so as a workaround:
https://github.com/pygae/galgebra/blob/0366454409fb0ba5c6c9f3509ec886685ad52fdc/galgebra/mv.py#L91-L94
Note that if `__str__` is not defined, it defaults to `__repr__` - so we can save some lines by only defining the latter.
=> Do not make any __str__ or __repr__ output latex

examples/ipython/simple_ga_test.ipynb, galgebra/lt.py, galgebra/mv.py, galgebra/printer.py
Follow-up to #369, I forgot to check `lt.py` for the same pattern.
`Mlt.Fmt` was a weird outlier that called `print` rather than returning an object to be printed.
`Lt.Fmt` had the same code commented out, so I guess this was just an incomplete transition to the return-style of `Fmt`.
The main effect of this will be to fix plaintext output in ipython of `Lt` and `Mlt` instances. I suspect we have no tests for that, but thankfully almost all of this code path is shared by `Mv` and `Dop`, so I think that's ok.
=> Also fix `Fmt` to work correctly on Lt and Mlt instances

galgebra/mv.py, galgebra/printer.py
This function's use-case appeared to be to force blades to print as bases.
However, this isn't at all obvious from the name, and the arguments which can be passed in look outright dangerous.
Additionally, this only worked for plaintext printing, not for LaTeX.
If users want to print the base representation, they can just print `some_mv.base_rep()` instead.
If users want to perform arbitrary and meaningless textual substitutions, we should let them do so explicitly themselves.
This reverts e5a64934c2f965695e69440dbd49817bad0c017a
=> Remove the unused and undocumented `printer.print_replace`

galgebra/dop.py, galgebra/lt.py, galgebra/mv.py, galgebra/printer.py
It's easier to make these a base class than it is to import them separately at each layer.
This also:
* Fixes `Sdop._repr_latex_` and `Pdop._repr_latex_`, which forgot to enter math mode (by removing their broken implementations).
* Removes `Dop.title`, which was always `None`, never set, and not used until a very recent commit.
* Simplifies `_FmtResult` to always have a title.
=> Simplify the common printing methods between classes

examples/LaTeX/curvi_linear_latex.py, examples/LaTeX/diffeq_sys.py, examples/LaTeX/em_waves_latex.py, examples/LaTeX/groups.py, examples/LaTeX/latex_check.py, examples/LaTeX/lin_tran_check.py, examples/LaTeX/linear_EM_waves.py, examples/LaTeX/physics_check_latex.py, examples/LaTeX/simple_check_latex.py, examples/Old Format/latex_check.py, examples/Old Format/mv_setup_options.py, examples/Old Format/outdated/manifold_check.py, examples/Old Format/outdated/manifold_check_latex.py, examples/Old Format/physics_check_latex.py, examples/Old Format/simple_check_latex.py, examples/Old Format/spherical_latex.py, examples/Old Format/terminal_check.py, examples/Terminal/coefs_test.py, examples/Terminal/mv_setup_options.py, examples/Terminal/terminal_check.py
These were a workaround for our old implementation of `galgebra.printer.Get_Function` being broken.
It is not longer broken because we now use `inspect.getsource` internally.
=> Remove dummy functions

examples/ipython/printing-galgebra.ipynb
sympy/sympy@e31c4cdedb5080325b3fd04f4b4826d9dab65b26 (sympy/sympy#19389)
The upstream change is in our favor, but it breaks our tests that were demonstrating previously-broken behavior.
For now, we tag those tests with `NBVAL_IGNORE_OUTPUT` to avoid them failing on released versions of sympy.
The other changes in this file are already covered by our nbval sanitization configuration.
=> Update notebook to the behavior from sympy@e31c4cdedb5080325b3fd04f4b4826d9dab65b26

.circleci/config.yml, doc/conf.py, doc/index.rst, doc/readthedocs-pip-requirements.txt, doc/tutorials/algebra.nblink, examples/ipython/tutorial_algebra.ipynb
I've included a commit with his version unmodified, in the hope that it makes merging them together in future easier.
Even if we haven't settled on a "new printer" API, we still could really do with basic tutorials in the docs.
I'll follow up with his calculus tutorial later.
---
Tutorial appears on the docs here: https://galgebra--375.org.readthedocs.build/en/375/tutorials/algebra.html
=> Add a tutorial taken from Alan's branch

doc/module-components.rst
This will also make the eventual conversion to automethod etc easier (xref gh-300)
=> Use fully-qualified names in the module-components docs [ci skip]

doc/conf.py, galgebra/atoms.py
As an example, this page is now much easier to read:
https://galgebra--401.org.readthedocs.build/en/401/generated/galgebra.atoms.html#module-galgebra.atoms
=> Small fixes to documentation

doc/_sphinxext/releases_hack.py, doc/conf.py
Our tag names start with v, but the default for releases is to not use a v.
https://galgebra--407.org.readthedocs.build/en/407/changelog.html
This fixes the tags, but breaks the "next release" link...
xref https://github.com/bitprophet/releases/issues/65
=> Fix the broken release links to include the v [ci skip]

README.md, doc/_sphinxext/md_include.py, doc/bundled-resources.rst, doc/conf.py, doc/getting-started.rst, doc/index.rst, doc/installation.rst, doc/migration.rst, doc/readthedocs-pip-requirements.txt
See commit messages
New TOC is:
https://galgebra--413.org.readthedocs.build/en/413/
xref https://github.com/readthedocs/recommonmark/issues/191, which I should upstream to at some point.
-----
[View rendered README.md](https://github.com/eric-wieser/galgebra/blob/use-recommonmark/README.md)
=> Split the readme into standalone documentation pages

doc/_templates/layout.html, doc/conf.py
=> Use LaTeX to show the galgebra logo in the top left

README.md
The first of these is deprecated, the last two are not public API and should be spelt `S.One` and `S.Zero`.
Part of gh-394
-----
[View rendered README.md](https://github.com/pygae/galgebra/blob/eric-wieser/one-zero-readme/README.md)
=> Remove Get_Program, one, and zero from example imports

README.md
Address the second bullet point in #394.
-----
[View rendered README.md](https://github.com/pygae/galgebra/blob/update-migration-guide/README.md)
=> Update Migration Guide to mention API changes  [ci skip]

README.md
- change it to one badge per line
- move coverage left since it's our primary tracking indicator
- remove codacy badges since we have removed it
- add LGTM and CodeClimate badges
This should resolve #220 .
The result looks like this:
-----
[View rendered README.md](https://github.com/pygae/galgebra/blob/quality-badges/README.md)
=> Update code quality badges [ci skip] 

galgebra/atoms.py, galgebra/dop.py, galgebra/lt.py, galgebra/mv.py, galgebra/printer.py
This fixes the mistake described as the first item in https://docs.sympy.org/dev/modules/printing.html#common-mistakes
CI will continue to fail on sympy-master with and without this patch, but I think we should merge it as long as it keeps passing on the other CI runs.
=> Fix printing antipattern

galgebra/printer.py
Patching `Basic.__repr__` results in the pretty-printer on `SympyPrintable` being ignored, which makes the notebook tests fail CI.
If we patch `SympyPrintable.__repr__` instead, then the pretty-printer is still respected.
Note that `sympy.printing.defaults.Printable` is new in the unreleased sympy 1.7
---
To make CI pass, this will need (at least) sympy/sympy#19902, which should now be merged.
A failing CI run from before this patch with 13 failures: https://app.circleci.com/pipelines/github/pygae/galgebra/1134/workflows/3944fa71-53e0-4eff-ad91-d57e26a223d8/jobs/6545
One from after this patch with only 7 failures:
https://app.circleci.com/pipelines/github/pygae/galgebra/1137/workflows/d6e511b1-82a8-4825-bd35-9013d5a3bb43/jobs/6572/tests
=> Patch the new sympy printing base class instead of Basic

examples/ipython/Smith Sphere.ipynb, examples/ipython/dop.ipynb, examples/ipython/gsym-printing.ipynb, examples/ipython/inner_product.ipynb, examples/ipython/printing-galgebra.ipynb, examples/ipython/second_derivative.ipynb, examples/ipython/simple_ga_test.ipynb, examples/ipython/st4.ipynb, examples/ipython/tutorial_algebra.ipynb, examples/ipython/verify_doc_python.ipynb, galgebra/printer.py
Annoyingly this results in a massive diff removing spaces in every file.
Making this change will eventually allow us to remove `GaPrintable._repr_latex_` entirely, in favor of using sympy builtins.
LaTeX does not care about the presence or absence of these spaces.
(note: this PR summary has typo fixes not present in the commit message!)
=> Let sympy handle wrapping with `equation*`

.circleci/config.yml, examples/ipython/Smith Sphere.ipynb, examples/ipython/dop.ipynb, examples/ipython/gr_metrics.ipynb, examples/ipython/gsym-printing.ipynb, examples/ipython/printing-galgebra.ipynb, examples/ipython/verify_doc_python.ipynb, galgebra/printer.py, setup.py
This makes the default `_repr_latex_` of all sympy objects use our printer, and does so in a way that is easy for the user to reconfigure.
We switch to `latex_mode="equation*"` because it is more consistent with our existing `_repr_latex_`.
---
Note that `latex_mode="equation*"` did not work before #439.
The main motivation here is dogfooding - our tutorial notebook already configures sympy in this way, so we should use it this way in our tests too.
Eventually, I'd envisage pushing `Format` to the status of a deprecated API, and encouraging users to call `sympy.init_printing()` directly or perhaps a new `galgebra.printer.init_printing()` which defaults an argument or two.
=> Use our printer as the default in jupyter

examples/ipython/gsym-printing.ipynb, examples/ipython/printing-galgebra.ipynb, examples/ipython/tutorial_algebra.ipynb, galgebra/printer.py
In sympy 1.7, we can use the new base class to inherit the printer.
In earlier versions, we have to poke around in IPython internals to find the appropriate printer.
This means that `GaLatexPrinter` is no longer used by default, but that's ok because:
* All our examples either call `Format` to enable it, or use `init_printing`
* `GaLatexPrinter` no longer does anything essential like it used to - all galgebra objects print to latex without it, all it adds is subjective tweaks to:
* Determinant printing
* Derivative printing
* Function printing (omitting arguments, subscripts)
=> Respect customizations made in sympy.init_printing

galgebra/_utils/printable.py, galgebra/printer.py
Since this is a temporary solution until we drop sympy 1.6, putting it in its own file keeps it isolated.
=> Move the backport of sympy.Printable into its own file

galgebra/dop.py, galgebra/ga.py, galgebra/lt.py, galgebra/metric.py, galgebra/mv.py, test/test_test.py
We don't need these at all, sympy provides them as `S.One`, `S.Half`, and `S.Zero`.
Note that `S.One` is about 20x faster than `S(1)`, although this won't really make any difference.
Unlike #267, this does not remove the ones that are used in examples from the public API.
=> Remove all the duplicate spellings of one/half/zero

doc/changelog.rst, galgebra/printer.py
All it's methods and attributes were static, and the instances were never used.
This replaces the class `Eprint` with a single function `Eprint`, which just changes global settings on the `GaPrinter` object.
Release note entry here links to the function docs: https://galgebra--450.org.readthedocs.build/en/450/changelog.html
=> Cleanup the very weird `Eprint` class which does not behave like a class at all

doc/changelog.rst, galgebra/lt.py, test/test_lt.py
These properties aren't used, and their existance makes it impossible to use the `Lt` class on coord-less `GA` objects.
=> Deprecate lt.coords and lt.X

galgebra/lt.py, test/test_lt.py
This includes a deprecation of two properties that were probably intended to be private anyway,
Docs are at https://galgebra--460.org.readthedocs.build/en/460/generated/galgebra.lt.html#galgebra.lt.Lt
=> More cleanups to Lt

galgebra/metric.py, test/test_test.py
The intent here was likely to just avoid normalizing `de` if `de is None`, and this change brings the implementation in line with the intent.
Fixes #466, cc @greg1950
=> BUG: metric: Do not skip normalization just because `de is None`

examples/LaTeX/print_check_latex.py
By being a little more explicit about the simplification, we can get this test to pass.
Closes #441, assuming it works.
=> Fix CI failure on sympy master

doc/conf.py, doc/readthedocs-pip-requirements.txt
We don't seem to use this, and it isn't installing properly on readthedocs any more.
=> Fix readthedocs builds

.circleci/config.yml, examples/ipython/galgebra_ipython_helpers.py, setup.py, test_requirements.txt
Python 3.5 is well past its EOL, ad Python 3.9 has been out for 6 months or so. Rather than overloading CI, let's drop one and add the other.
While we're here, let's test on a newer sympy version (1.7).
=> Drop Python 3.5, bump the sympy version

test/test_test.py
A small refactor of a test, extracted from #452. This makes the test less fragile to changes in how the printer hacks are set up - which is good, because its not trying to test the printer, but the results.
=> Change tests to directly test the printer, rather than `__str__`.

.circleci/config.yml, galgebra/mv.py, setup.py
The CircleCI configuration has rotted over time. This gets it functioning again, if only so that we have something to compare against the proposed switch to github actions.
=> Get CircleCI working again

README.md, doc/conf.py, doc/getting-started.rst, doc/index.rst, doc/readthedocs-pip-requirements.txt
=> Replace SVGs of LaTeX to just LaTeX

README.md, setup.py
- Drop support for Python 3.5-3.7
- Be clear and consistent about the supported Python and SymPy versions
=> Be clear and consistent about the supported Python and SymPy versions

.github/workflows/ci.yml, galgebra/_version.py
See
- https://github.com/pypa/gh-action-pypi-publish/tree/release/v1/?tab=readme-ov-file#trusted-publishing
- https://docs.pypi.org/trusted-publishers/adding-a-publisher/
- maintainers please check https://pypi.org/manage/project/galgebra/settings/publishing/ as I have set up the trusted publishing for pygae/galgebra there
=> Set up pypi publish with trusted-publishing

README.md, doc/changelog.rst, galgebra/_version.py
This release is a maintenance release with no functionality changes, includes only some updates to README:
- citation info (716617a380a6eb5d5746b503db0baefcf6a66660...4607cdaf35958f5e955fe22e71155752ca7be230)
- star history
- contributors
This also fixes the issue that zenodo can't correctly refer to v0.5.1 due to how I messed up with releasing 0.5.1:
> I created release 0.5.1rc2 but the version number in `_version.py` is `0.5.1` so pypi release `0.5.1` and I can't release `0.5.1` again after that, so I modified the release on Github, but zenodo can only point to 0.5.1rc2.
Another things that I have messed up is that I forgot to use squash merge during 0.5.1 and 0.5.2. Since 0.6.0, this practice would be resumed.
=> Release 0.5.2

README.md, doc/bundled-resources.rst, doc/conf.py, doc/getting-started.rst, doc/index.rst, doc/installation.rst, doc/migration.rst, doc/old_migration_guide.md, doc/readthedocs-pip-requirements.txt
=> Clarifications for migration guides

README.md, doc/used_by.md
Add information on how GAlgebra is used in other projects.
It's worth it to keep it inside the repo, and not as a hanging issue.
This list provides information on GAlgebra's usefulness for some, and these downstream projects can be used to validate the GAlgebra against them.
~~This list has not yet include results of tracing citations, which is also worth gathering.~~ (done)
I'll leave the PR open a bit for feedback.
=> Add "Used by"

galgebra/mv.py, test/test_mv.py
Add `shirokov_inverse` and `hitzer_inverse` functions, based on the `clifford` package implementation of the [shirokov_inverse](https://github.com/pygae/clifford/blob/master/clifford/_layout.py#L574) and [hitzer_inverse](https://github.com/pygae/clifford/blob/master/clifford/_layout.py#L592).
closes #529
=> Add shirokov_inverse and hitzer_inverse
