- galgebra/ga.py
- galgebra/metric.py
- galgebra/mv.py
- galgebra/printer.py
Extracted from https://github.com/pygae/galgebra/compare/master...abrombo:master
> Remove trailing spaces in main code

- .lgtm.yml
> Add LGTM configuration to ignore example files

- galgebra/ga.py
- galgebra/lt.py
- galgebra/metric.py
- galgebra/mv.py
Found using LGTM.com
Also sort them in the recommended builtin, third-party, first-party order
> Remove unused imports

- doc/changelog.rst
Please feel free to edit via github @utensil to remove entries you don't think are release-note worthy
[Rendered here](https://external-builds.readthedocs.io/html/galgebra/85/changelog.html)
> Update changelog entries from recent PRs

- galgebra/metric.py
This should address some CI warnings about deeply nested functions.
Result:
> Extract a helper function from `metric_symbols_list`

- doc/changelog.rst
https://external-builds.readthedocs.io/html/galgebra/146/changelog.html
> Update release notes from some previous PRs

- .circleci/config.yml
- .travis.yml
- test_requirements.txt
Works around https://github.com/computationalmodelling/nbval/issues/129
> Pin coverage before 5.0.0

- .mailmap
I've avoided putting any of his active email addresses here for spam reasons.
> Add mailmap to merge Alan's old usernames

- .circleci/config.yml
From https://circleci.com/docs/2.0/collect-test-data/#pytest
> Save test data to circle-ci

- galgebra/__init__.py
- galgebra/_version.py
- setup.py
This uses the same approach as clifford and pyganja
> Add `galgebra.__version__` for easy version inspection

- galgebra/mv.py
Blocked by gh-183 (edit: now merged)
> Extract duplicated consolidation code to helper functions

- galgebra/mv.py
This makes Sdop a little more consistent with Dop.
As spotted by @utensil in #189
> Unpack tuples by name for clarity

- galgebra/mv.py
The only differences were:
* The variable names
* A missing consolidation step in `__call__`
> Merge the equivalent `Sdop.__call__` and `Sdop.__mul__`

- galgebra/ga.py
- galgebra/mv.py
- test/test_mv.py
Haven't implemented hashing on `pdop` etc, since that's more work.
I expect this to fix some LGTM warnings.
> Fixes to equality and hashing

- .circleci/config.yml
- galgebra/_version.py
Following https://circleci.com/docs/2.0/configuration-reference/#tags , using 0.4.5rc3 to verify.
> Support trigger CircleCI publish by tags

- galgebra/mv.py
Instead this uses the sympy `sort_key` API. This fixes two bugs:
* `Pdop.compare` no longer raises `ValueError` if the symbol is not in `Ga.coords`
* `Pdop.compare` does the right thing if there are more than 9 coordinates.
Previously string concatenation was used, which would sort `x_{10}` badly when compared to `x_1` and `x_0`.
Split from #201, as the cleanup without the printing change.
> Replace Pdop.compare with a key function

- README.md
We now support 1.5 too.
-----
[View rendered README.md](https://github.com/pygae/galgebra/blob/eric-wieser-patch-1/README.md)
> Remove comments about Sympy 1.3

- doc/changelog.rst
Also move some existing notes.
> Add missing release notes for previous PRs

- .circleci/config.yml
- examples/ipython/LaTeX.ipynb
- examples/ipython/Old Format.ipynb
- examples/ipython/Smith Sphere.ipynb
- examples/ipython/Terminal.ipynb
- examples/ipython/colored_christoffel_symbols.ipynb
- examples/ipython/dop.ipynb
- examples/ipython/gr_metrics.ipynb
- examples/ipython/inner_product.ipynb
- examples/ipython/second_derivative.ipynb
- examples/ipython/simple_ga_test.ipynb
- examples/ipython/verify_doc_python.ipynb
- test_requirements.txt
- Run CI against SymPy 1.5 as well as 1.4 and 1.3
- Regenerate notebooks using Sympy 1.5
> Officially supports SymPy 1.5

- galgebra/deprecated.py
- galgebra/ga.py
The intent here was to just create a scalar, not to create a weirdly named variable.
Relates to #213
> Cleanup ReciprocalFrame

- galgebra/metric.py
This removes some duplicated logic
> Use apply_function_list in Simp.apply

- galgebra/ga.py
- galgebra/metric.py
- galgebra/mv.py
These have been reformatted a little to take advantage of Sphinx
> Cherry-pick comments from @abrombo's branch

- galgebra/ga.py
These aren't needed, since `blades_to_grades_dict` and `indexes_to_bases_dict` contain `S(1)` already.
> Remove more special cases for scalars

- .circleci/config.yml
- setup.cfg
Deliberately removed some ignores to prove this fails. Will fix them later.
> Fix flake8 runner to not be a no-op

- doc/conf.py
- doc/readthedocs-pip-requirements.txt
Note that m2r is not compatible with this - my hope is we didn't need it anyway.
> Bump sphinx to 3.0

- galgebra/deprecated.py
- galgebra/dop.py
- galgebra/ga.py
- galgebra/lt.py
- galgebra/metric.py
- galgebra/mv.py
- galgebra/printer.py
- setup.cfg
- test/test_lt.py
- test/test_mv.py
- test/test_test.py
The comma spacing resolves a flake8 warning
> Tidy redundant tuple parentheses and bad comma spacing

- galgebra/ga.py
Primarily motivating by saving a bunch of lines.
This attribute is undocumented, so it shouldn't matter if we change it.
> Make blade_superscripts a GradedTuple too

- galgebra/ga.py
It's a little easier to see the pattern in this big function if we split out some helpers.
> Split `_build_bases` into a handful of smaller functions

- galgebra/_backports/__init__.py
- galgebra/_backports/typing.py
- galgebra/ga.py
- test/test_misc.py
Adds a test too, since this is fiddly.
> Fix OrderedBiMap so that it works in annotations

- galgebra/ga.py
> Remove `Ga.deriv` which is undocumented and unused

- galgebra/printer.py
This code is an exact duplicate of the code in sympy/sympy@e81f06a7d429f2d6bc648c06b4e4e14da0f539c3
> Replace copied code with an import

- galgebra/metric.py
This makes the existing logic a little easier to follow
> Use `any` and `all` in place of loops with `break`

- doc/readthedocs-pip-requirements.txt
- galgebra/_utils/__init__.py
- galgebra/_utils/cached_property.py
- galgebra/ga.py
- test/test_misc.py
A reduced version of #252, which will hopefully pass CI.
This seems to go with the spirit of https://github.com/pygae/galgebra/pull/78#pullrequestreview-323373088
> Use cached_property for much of `Ga`

- galgebra/metric.py
The `Rational` constructor already handles this
> Remove special case for fractions

- galgebra/metric.py
- setup.cfg
LGTM flagged this up in another PR, submitting separately keeps the comment noise down.
> Remove an unused local variable

- doc/galgebra_guide.rst
> Fix other references

- galgebra/_utils/parser.py
- galgebra/printer.py
Whether this belongs in the `galgebra.printer` namespace at all is a different question, to be addressed another time.
> Move the Gaeval parser to its own file

- galgebra/mv.py
As requested by @utensil in gh-303
> Add a random selection of type annotations

- examples/ipython/LaTeX.ipynb
- examples/ipython/Old Format.ipynb
- examples/ipython/galgebra_ipython_helpers.py
> Extract duplicated helper code from the notebooks spawning python interpreters

- doc/module-components.rst
Scroll up above https://galgebra--311.org.readthedocs.build/en/311/module-components.html#instantiating-a-multivector.
> Convert table of method and class names to links [ci skip]

- doc/galgebra_guide.rst
- galgebra/printer.py
This one had a handy example, which was worth keeping.
xref gh-300
> Merge a second (!) duplicate of the GaEval docstrings

- doc/changelog.rst
- galgebra/ga.py
This is what all my `Dop` work in the past was building up to.
> Add support for multivector derivative operators

- .circleci/config.yml
- test/.nbval_sanitize.cfg
> Add a CI build for SymPy master

- test/test_test.py
> Add a test for make_grad on custom vectors and bivectors

- galgebra/printer.py
This will be less fragile, and is also shorter.
It's likely there'll be some minor latex output difference (extra blank lines etc), hence the draft status.
> Use the `inspect` module to implement `Print_Function`

- galgebra/printer.py
- test/test_printer.py
Should bump up coverage a bit.
There are some bugs in this code too, which I'll address after these tests are committed.
> Add tests for oprint

- galgebra/mv.py
- test/test_mv.py
We might want to consider deprecating this in a future PR.
> Implement Mv.list in terms of Mv.blade_coefs

- galgebra/printer.py
The sympy way is to store these in a per-instance `_settings` dict.
This patch makes the assumption that the attributes of `GaLatexPrinter` were not public API, and that user code should only be accessing them through `Format`.
This means that the galgebra printer now respects the `inv_trig_style` argument to `sympy.init_printing`.
> Move global settings out of GaLatexPrinter

- .zenodo.json
Based off the one from pygae/clifford.
I just added the zenodo webhook, so it should end up published after we do our next release.
> Create a zenodo metadata file

- galgebra/printer.py
Seem commit messages - one of these was a no-op assignment, the other is completely unused.
> Tidy some more static variables

- doc/changelog.rst
https://galgebra--389.org.readthedocs.build/en/389/changelog.html
Not a final changelog, but this should cover most of the changes. I'll add any I've missed in a follow-up PR.
> Update the changelog to reflect merged PRs

- galgebra/mv.py
- test/test_mv.py
> Do not crash when subtracting a scalar from a multivector

- doc/changelog.rst
- galgebra/metric.py
- test/test_test.py
Fixes #312, and also updates the changelog with information about the changes that led to this deprecation.
> Add missing tests for deprecations

- doc/changelog.rst
https://galgebra--397.org.readthedocs.build/en/397/changelog.html
> Add some missed changelog entries

- README.md
-----
[View rendered README.md](https://github.com/pygae/galgebra/blob/eric-wieser/zenodo-badge/README.md)
> Add a zenodo badge

- doc/conf.py
- examples/ipython/tutorial_algebra.ipynb
https://galgebra--417.org.readthedocs.build/en/417/tutorials/algebra.html
> Add links to the notebook for the tutorial

- galgebra/printer.py
The docstring for GaLatexPrinter was really a description of the module in general.
This docstring has been moved to the module docstrnig, and new docstrings written for `GaLatexPrinter` and `GaStrPrinter`.
https://galgebra--420.org.readthedocs.build/en/420/generated/galgebra.printer.html#module-galgebra.printer
> Improve docstrings in printer.py

- doc/changelog.rst
- galgebra/mv.py
- test/test_mv.py
> Fix incorrect right and left contraction on scalars

- doc/changelog.rst
- galgebra/ga.py
- galgebra/metric.py
- test/test_test.py
Support for just one basis is needed for dual numbers, cc @tBuLi.
> Allow algebras with only 1 or even 0 basis vectors

- .circleci/config.yml
- test_requirements.txt
> Do not use pytest-xdist on python 3.5

- galgebra/lt.py
- test/test_lt.py
See commit messages for details.
> Various cleanups and fixes to Lt

- doc/conf.py
- doc/readthedocs-pip-requirements.txt
The bullet points aren't rendering correctly for some reason.
> Fix broken stylesheet in the docs

- doc/conf.py
- doc/galgebra_guide.rst
- doc/module-components.rst
- doc/readthedocs-pip-requirements.txt
- doc/sympy-representation.rst
> Fix the doc render

- examples/ipython/gsym-printing.ipynb
- galgebra/atoms.py
> A workaround for the broken `MatrixFunction`
